version: '3.7'
services:
  elasticsearch:
    image: public.ecr.aws/opensearchproject/opensearch:2.7.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false #disable security
      - discovery.type=single-node #run as single node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
    driver: local